Repository film-fly/FilmFly, pull requests merged in 2024-07, with the labels that each got.

#13 [FEAT]: 리뷰 등록
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewCreateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewRequestDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/entity/Review.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
Labels: enhancement

#32 이메일 인증 설정
  src/main/java/com/sparta/filmfly/domain/user/controller/EmailVerificationController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/EmailSendRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/LoginRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/SignupRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/EmailVerification.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: bug

#34 리뷰 단일, 전체 조회 구현 완료
  src/main/java/com/sparta/filmfly/domain/movie/entity/Movie.java
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/util/PageUtils.java
Labels: enhancement

#36 리뷰 수정
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewUpdateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/review/entity/Review.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
Labels: enhancement

#37 보드 생성
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardRequestDto.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/entity/Board.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
Labels: enhancement

#38 리뷰 삭제 구현 완료
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/entity/Review.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/NotOwnerException.java
Labels: enhancement

#35 토큰전달방식 헤더에서 쿠키 전달 방식으로 수정
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
Labels: wontfix

#41 좋아요 기능
  src/main/java/com/sparta/filmfly/domain/reaction/ReactionContentTypeEnum.java
  src/main/java/com/sparta/filmfly/domain/reaction/controller/GoodController.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/BadAddRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/GoodAddRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/GoodRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/entity/Good.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/GoodRepository.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/GoodService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/AlreadyActionException.java
  src/test/http/ReactionHttp.http
Labels: enhancement

#44 좋아요 취소
  src/main/java/com/sparta/filmfly/domain/reaction/controller/GoodController.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/GoodRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/GoodService.java
  src/test/http/ReactionHttp.http
Labels: enhancement

#46 싫어요 등록
  src/main/java/com/sparta/filmfly/domain/reaction/controller/BadController.java
  src/main/java/com/sparta/filmfly/domain/reaction/controller/GoodController.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/BadAddRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/BadRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/entity/Bad.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/BadRepository.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/BadService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/test/http/ReactionHttp.http
Labels: enhancement

#48 싫어요 취소
  src/main/java/com/sparta/filmfly/domain/reaction/controller/BadController.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/BadService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/test/http/ReactionHttp.http
Labels: enhancement

#49 보드 조회
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/repository/BoardRepository.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#52 보드 수정
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/entity/Board.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
Labels: enhancement

#55 소셜로그인 구현
  build.gradle
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/KakaoUserInfoDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/TokenResponseDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/service/KakaoService.java
  src/main/java/com/sparta/filmfly/global/auth/JwtProvider.java
  src/main/java/com/sparta/filmfly/global/config/RestTemplateConfig.java
  src/main/resources/application.yml
Labels: enhancement

#56 보드 삭제
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/entity/Board.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
Labels: enhancement

#62 회원가입, 로그인 프론트 구현
  front/css/style.css
  front/html/login.html
  front/html/signup.html
  front/images/kakao_login.png
Labels: enhancement

#64 댓글 생성
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/entity/Comment.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#65 댓글 조회 생성
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
Labels: enhancement

#66 댓글 수정
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/entity/Comment.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
Labels: enhancement

#67 [FEAT] 댓글 삭제 생성
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/entity/Comment.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
Labels: enhancement

#70 [FEAT] 유저 비밀번호 변경 구현
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/PasswordUpdateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#73 회원가입, 로그인 ,이미일인증, 소셜로그인 ,비밀번호 변경 구현
  build.gradle
  src/main/java/com/sparta/filmfly/domain/user/controller/EmailVerificationController.java
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/EmailVerificationRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/KakaoUserInfoDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/LoginRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/PasswordUpdateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/SignupRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/TokenResponseDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserResponseDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/EmailVerification.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/entity/UserStatusEnum.java
  src/main/java/com/sparta/filmfly/domain/user/repository/EmailVerificationRepository.java
  src/main/java/com/sparta/filmfly/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/filmfly/domain/user/service/EmailVerificationService.java
  src/main/java/com/sparta/filmfly/domain/user/service/KakaoService.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtProvider.java
  src/main/java/com/sparta/filmfly/global/auth/UserDetailsImpl.java
  src/main/java/com/sparta/filmfly/global/auth/UserDetailsServiceImpl.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/config/PasswordConfig.java
  src/main/java/com/sparta/filmfly/global/config/RestTemplateConfig.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/AccessDeniedException.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/DuplicateException.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/ExpiredException.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/InformationMismatchException.java
  src/main/resources/application.yml
  src/test/http/HttpExamRequest.http
Labels: enhancement

#77 프로필 업로드기능
  build.gradle
  front/common/common-header.html
  front/css/reset.css
  front/css/style.css
  front/html/exam.html
  front/html/index.html
  front/images/logo.png
  front/js/common.js
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/ProfileUpdateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/common/OctetStreamReadMsgConverter.java
  src/main/java/com/sparta/filmfly/global/common/S3Uploader.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/config/AwsS3Config.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/UploadException.java
  src/main/resources/application.yml
Labels: enhancement

#81 [BUGFIX] JWT base64 인코딩 특수문자 생성 오류
  src/main/java/com/sparta/filmfly/global/auth/JwtProvider.java
  src/test/http/HttpLoginTokenTest.http
  src/test/http/HttpPasswordModifyTest.http
Labels: bug

#82 프로필 조회 기능
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserResponseDto.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
Labels: enhancement

#83 보드 CRUD 유저 부분 추가
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/entity/Board.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#86 댓글 crud 유저 부분 추가
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/entity/Comment.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#88 BoardResponseDto에 id 값 추가
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardResponseDto.java
Labels: enhancement

#90 유저 회원탈퇴 기능 구현
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/AccountDeleteRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
Labels: enhancement

#91 보드 http api 테스트 추가
  src/test/http/HttpBoardRequest.http
Labels: enhancement

#93 API Test 잘못 올린 부분 수정
  src/test/http/HttpCommentRequest.http
Labels: enhancement

#95 [FEAT] 유저상세 조회기능 구현(관리자 기능)
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserResponseDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserSearchRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#96 상태별 유저 조회기능 구현(관리자 기능)
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserStatusRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserStatusResponseDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
Labels: enhancement

#97 유저 정지 시키는 기능 구현
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/InvalidTargetException.java
Labels: enhancement

#98 유저 활성화 시키는 기능 구현
  build.gradle
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/AccountDeleteRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/ProfileUpdateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserResponseDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserSearchRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserStatusRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserStatusResponseDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtProvider.java
  src/main/java/com/sparta/filmfly/global/common/OctetStreamReadMsgConverter.java
  src/main/java/com/sparta/filmfly/global/common/S3Uploader.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/config/AwsS3Config.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/InvalidTargetException.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/UploadException.java
  src/main/resources/application.yml
  src/test/http/HttpLoginTokenTest.http
  src/test/http/HttpPasswordModifyTest.http
Labels: enhancement

#103 유저 차단 기능 구현
  src/main/java/com/sparta/filmfly/domain/block/controller/BlockController.java
  src/main/java/com/sparta/filmfly/domain/block/dto/BlockRequestDto.java
  src/main/java/com/sparta/filmfly/domain/block/entity/Block.java
  src/main/java/com/sparta/filmfly/domain/block/repository/BlockRepository.java
  src/main/java/com/sparta/filmfly/domain/block/service/BlockService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#104 내가 차단한 유저 목록 조회 기능 구현
  src/main/java/com/sparta/filmfly/domain/block/controller/BlockController.java
  src/main/java/com/sparta/filmfly/domain/block/dto/BlockedUserResponseDto.java
  src/main/java/com/sparta/filmfly/domain/block/repository/BlockRepository.java
  src/main/java/com/sparta/filmfly/domain/block/service/BlockService.java
Labels: enhancement

#105 유저 차단 해제 기능 구현
  src/main/java/com/sparta/filmfly/domain/block/controller/BlockController.java
  src/main/java/com/sparta/filmfly/domain/block/dto/BlockRequestDto.java
  src/main/java/com/sparta/filmfly/domain/block/repository/BlockRepository.java
  src/main/java/com/sparta/filmfly/domain/block/service/BlockService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#109 유저 신고 기능 구현
  src/main/java/com/sparta/filmfly/domain/block/controller/BlockController.java
  src/main/java/com/sparta/filmfly/domain/report/controller/ReportController.java
  src/main/java/com/sparta/filmfly/domain/report/dto/ReportRequestDto.java
  src/main/java/com/sparta/filmfly/domain/report/entity/Report.java
  src/main/java/com/sparta/filmfly/domain/report/repository/ReportRepository.java
  src/main/java/com/sparta/filmfly/domain/report/service/ReportService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#110 신고 목록 조회 기능 구현
  src/main/java/com/sparta/filmfly/domain/report/controller/ReportController.java
  src/main/java/com/sparta/filmfly/domain/report/dto/ReportResponseDto.java
  src/main/java/com/sparta/filmfly/domain/report/entity/Report.java
  src/main/java/com/sparta/filmfly/domain/report/repository/ReportRepository.java
  src/main/java/com/sparta/filmfly/domain/report/service/ReportService.java
Labels: enhancement

#111 유저 기능 구현
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/InvalidTargetException.java
Labels: enhancement

#117 유저 닉네임 필수값으로 변경
  src/main/java/com/sparta/filmfly/domain/user/dto/SignupRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
Labels: wontfix

#118 보드 파일 업로드 추가
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/domain/media/dto/MediaResponseDto.java
  src/main/java/com/sparta/filmfly/domain/media/entity/Media.java
  src/main/java/com/sparta/filmfly/domain/media/repository/MediaRepository.java
  src/main/java/com/sparta/filmfly/domain/media/service/MediaService.java
  src/main/java/com/sparta/filmfly/global/common/S3Uploader.java
  src/test/http/HttpBoardRequest.http
Labels: enhancement

#121 보드, 미디어 코드 컨벤션 적용
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/entity/Board.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/domain/media/service/MediaService.java
Labels: enhancement

#119 마이 페이지 프론트만 구현
  front/css/style.css
  front/html/create-collection.html
  front/html/create-review.html
  front/html/exam.html
  front/html/login.html
  front/html/mypage-bad.html
  front/html/mypage-block.html
  front/html/mypage-board.html
  front/html/mypage-collection-detail.html
  front/html/mypage-collection.html
  front/html/mypage-comment.html
  front/html/mypage-coupon.html
  front/html/mypage-favorite-movie.html
  front/html/mypage-good.html
  front/html/mypage-review.html
  front/html/mypage.html
  front/html/signup.html
  front/images/kakao_login.png
  front/images/profileImg.png
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: enhancement

#124 댓글 코드 컨벤션 적용
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/entity/Comment.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
Labels: enhancement

#125 리뷰 기능 코드 컨벤션 적용
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
Labels: documentation

#128 보드 수정 시 미디어 db 수정
  src/main/java/com/sparta/filmfly/domain/media/service/MediaService.java
Labels: enhancement

#130 주석 추가 및 hits 카운트 추가
  src/main/java/com/sparta/filmfly/domain/board/entity/Board.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#132 댓글 주석 추가
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#136 ResponseCodeEnum 리뷰 도메인 구분
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#137 reivew 기능
  src/main/java/com/sparta/filmfly/domain/movie/entity/Movie.java
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewCreateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewRequestDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewUpdateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/review/entity/Review.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/NotOwnerException.java
  src/main/java/com/sparta/filmfly/global/util/PageUtils.java
  src/test/http/review/ReviewHttp.http
Labels: enhancement

#138 [REFACTOR] 보드 코드 리펙토링
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/domain/media/service/MediaService.java
  src/main/java/com/sparta/filmfly/global/common/S3Uploader.java
  src/test/http/HttpBoardRequest.http
Labels: enhancement

#133 board 기능
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardRequestDto.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/entity/Board.java
  src/main/java/com/sparta/filmfly/domain/board/repository/BoardRepository.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/domain/media/dto/MediaResponseDto.java
  src/main/java/com/sparta/filmfly/domain/media/entity/Media.java
  src/main/java/com/sparta/filmfly/domain/media/repository/MediaRepository.java
  src/main/java/com/sparta/filmfly/domain/media/service/MediaService.java
  src/main/java/com/sparta/filmfly/global/common/S3Uploader.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/test/http/HttpBoardRequest.http
Labels: enhancement

#142 [REFACTOR] 댓글 코드 리펙토링
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/entity/Comment.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
  src/test/http/HttpCommentRequest.http
Labels: enhancement

#143 comment 기능
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/entity/Comment.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/test/http/HttpCommentRequest.http
Labels: enhancement

#144 이메일 재전송 횟수 제한 설정
  src/main/java/com/sparta/filmfly/domain/user/entity/EmailVerification.java
  src/main/java/com/sparta/filmfly/domain/user/repository/EmailVerificationRepository.java
  src/main/java/com/sparta/filmfly/domain/user/service/EmailVerificationService.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/LimitedException.java
Labels: wontfix

#146 찜 등록
  src/main/java/com/sparta/filmfly/domain/favorite/controller/FavoriteController.java
  src/main/java/com/sparta/filmfly/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/sparta/filmfly/domain/favorite/service/FavoriteService.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepository.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/AlreadyExistsException.java
  src/test/http/favorite/CreateFavorite.http
Labels: enhancement

#151 [REFACTOR] 미디어 코드 리팩토링
  src/main/java/com/sparta/filmfly/domain/media/service/MediaService.java
  src/main/java/com/sparta/filmfly/global/util/FileUtils.java
Labels: enhancement

#152 찜 조회하기
  src/main/java/com/sparta/filmfly/domain/favorite/controller/FavoriteController.java
  src/main/java/com/sparta/filmfly/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/sparta/filmfly/domain/favorite/service/FavoriteService.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieResponseDto.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#154 찜 삭제
  src/main/java/com/sparta/filmfly/domain/favorite/controller/FavoriteController.java
  src/main/java/com/sparta/filmfly/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/sparta/filmfly/domain/favorite/service/FavoriteService.java
Labels: enhancement

#155 찜하기 기능
  src/main/java/com/sparta/filmfly/domain/favorite/controller/FavoriteController.java
  src/main/java/com/sparta/filmfly/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/sparta/filmfly/domain/favorite/service/FavoriteService.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepository.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/AlreadyExistsException.java
  src/main/resources/application.yml
  src/test/http/favorite/CreateFavorite.http
Labels: enhancement

#160 157 feat 보관함 생성
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/CollectionRequestDto.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/CollectionResponseDto.java
  src/main/java/com/sparta/filmfly/domain/collection/entity/MovieCollection.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/CollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
  src/main/java/com/sparta/filmfly/domain/favorite/controller/FavoriteController.java
  src/main/java/com/sparta/filmfly/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/sparta/filmfly/domain/favorite/service/FavoriteService.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepository.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/AlreadyExistsException.java
  src/main/resources/application.yml
  src/test/http/favorite/CreateFavorite.http
Labels: enhancement

#163 보관함 목록 조회
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/CollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
Labels: enhancement

#166 유저 컨벤션 적용 리펙토링 적용
  src/main/java/com/sparta/filmfly/domain/user/controller/EmailVerificationController.java
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/TokenResponseDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserDeleteRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserKakaoInfoDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserLoginRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserPasswordUpdateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserProfileUpdateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserSignupRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserStatusSearchRequestDto.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserStatusSearchResponseDto.java
  src/main/java/com/sparta/filmfly/domain/user/entity/EmailVerification.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/repository/EmailVerificationRepository.java
  src/main/java/com/sparta/filmfly/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/filmfly/domain/user/service/EmailVerificationService.java
  src/main/java/com/sparta/filmfly/domain/user/service/KakaoService.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtProvider.java
  src/main/java/com/sparta/filmfly/global/auth/UserDetailsImpl.java
  src/main/java/com/sparta/filmfly/global/auth/UserDetailsServiceImpl.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: wontfix

#168 보관함 삭제
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/entity/Collection.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/CollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#170 영화 프론트
  front/css/style.css
  front/html/movie-detail.html
  front/html/movie.html
  front/html/mypage-collection-detail.html
  front/html/mypage-collection.html
  front/html/review-detail.html
  front/js/reaction.js
Labels: enhancement

#190 보드 코드 리팩토링
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/domain/reaction/ReactionContentTypeEnum.java
  src/main/java/com/sparta/filmfly/domain/reaction/controller/BadController.java
  src/main/java/com/sparta/filmfly/domain/reaction/controller/GoodController.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/BadRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/GoodRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/entity/Bad.java
  src/main/java/com/sparta/filmfly/domain/reaction/entity/Good.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/BadRepository.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/GoodRepository.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/BadService.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/GoodService.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/ReactionService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/AlreadyActionException.java
  src/test/http/reaction/ReactionHttp.http
Labels: enhancement

#193 보관함에 영화 등록
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/MovieCollectionRequestDto.java
  src/main/java/com/sparta/filmfly/domain/collection/entity/Collection.java
  src/main/java/com/sparta/filmfly/domain/collection/entity/MovieCollection.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/MovieCollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#196 게시물 프론트
  front/html/board-detail.html
  front/html/board.html
  front/html/create-board.html
  front/html/movie-detail.html
  front/html/review-detail.html
  front/js/reaction.js
  front/js/summernote.js
  src/main/java/com/sparta/filmfly/domain/file/controller/FileController.java
  src/main/java/com/sparta/filmfly/domain/file/service/FileService.java
  src/main/java/com/sparta/filmfly/domain/file/util/FileUtils.java
  src/main/java/com/sparta/filmfly/global/config/WebConfig.java
  src/main/resources/static/front/html/create-board.html
  src/main/resources/static/front/js/summernote.js
Labels: enhancement

#198 댓글 입력 폼 생성
  front/html/board-detail.html
Labels: enhancement

#199 댓글 수정 프론트 구현
  front/html/board-detail.html
Labels: enhancement

#202 마이페이지 프로필 정보 프론트
  front/css/style.css
  front/html/mypage-update-profile.html
  front/html/mypage.html
Labels: enhancement

#204 index 프론트
  front/html/index.html
Labels: enhancement

#205 194 feat 보관함 상세 조회
  build.gradle
  front/css/style.css
  front/html/movie-detail.html
  front/html/movie.html
  front/html/mypage-collection-detail.html
  front/html/mypage-collection.html
  front/html/review-detail.html
  front/js/reaction.js
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/MovieCollectionDto.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/MovieCollectionResponseDto.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/MovieCollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
  src/main/java/com/sparta/filmfly/domain/coupon/controller/CouponController.java
  src/main/java/com/sparta/filmfly/domain/coupon/dto/CouponRequestDto.java
  src/main/java/com/sparta/filmfly/domain/coupon/dto/CouponResponseDto.java
  src/main/java/com/sparta/filmfly/domain/coupon/entity/Coupon.java
  src/main/java/com/sparta/filmfly/domain/coupon/entity/UserCoupon.java
  src/main/java/com/sparta/filmfly/domain/coupon/repository/CouponRepository.java
  src/main/java/com/sparta/filmfly/domain/coupon/repository/UserCouponRepository.java
  src/main/java/com/sparta/filmfly/domain/coupon/service/CouponService.java
  src/main/java/com/sparta/filmfly/domain/officeboard/controller/OfficeBoardController.java
  src/main/java/com/sparta/filmfly/domain/officeboard/dto/OfficeBoardRequestDto.java
  src/main/java/com/sparta/filmfly/domain/officeboard/dto/OfficeBoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/officeboard/entity/OfficeBoard.java
  src/main/java/com/sparta/filmfly/domain/officeboard/repository/OfficeBoardRepository.java
  src/main/java/com/sparta/filmfly/domain/officeboard/service/OfficeBoardService.java
  src/main/java/com/sparta/filmfly/global/common/TimeStampEntity.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/UnAuthorizedException.java
  src/main/java/com/sparta/filmfly/global/util/FileUtils.java
  src/test/http/HttpCouponRequest.http
  src/test/http/HttpOfficeBoardRequest.http
Labels: enhancement

#207 보관함에서 영화 삭제
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/MovieCollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#208 영화 보관함 기능
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/CollectionRequestDto.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/CollectionResponseDto.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/MovieCollectionDto.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/MovieCollectionRequestDto.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/MovieCollectionResponseDto.java
  src/main/java/com/sparta/filmfly/domain/collection/entity/Collection.java
  src/main/java/com/sparta/filmfly/domain/collection/entity/MovieCollection.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/CollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/MovieCollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#221 찜하기 RequestMapping 수정
  src/main/java/com/sparta/filmfly/domain/favorite/controller/FavoriteController.java
Labels: enhancement

#226 전체적인 프론트 수정
  front/css/style.css
  front/html/board-detail.html
  front/html/board.html
  front/html/create-review.html
  front/html/index.html
  front/html/login.html
  front/html/movie-detail.html
  front/html/movie.html
  front/html/mypage-bad.html
  front/html/mypage-collection-detail.html
  front/html/mypage-comment.html
  front/html/mypage-coupon.html
  front/html/mypage-favorite-movie.html
  front/html/mypage-good.html
  front/html/mypage-update-password.html
  front/html/mypage-update-profile.html
  front/html/mypage-update.html
  front/html/mypage.html
  front/html/review-detail.html
  front/html/review-recently.html
  front/html/signup.html
  front/js/reaction.js
Labels: enhancement

#182 리액션 기능
  src/main/java/com/sparta/filmfly/domain/reaction/ReactionContentTypeEnum.java
  src/main/java/com/sparta/filmfly/domain/reaction/controller/BadController.java
  src/main/java/com/sparta/filmfly/domain/reaction/controller/GoodController.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/BadRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/GoodRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/entity/Bad.java
  src/main/java/com/sparta/filmfly/domain/reaction/entity/Good.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/BadRepository.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/GoodRepository.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/BadService.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/GoodService.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/ReactionService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/AlreadyActionException.java
  src/test/http/reaction/ReactionHttp.http
Labels: enhancement

#237 웹에 access, refresh 토큰 생성 안되던 문제 해결
  front/html/login.html
  src/main/java/com/sparta/filmfly/SpringInitTemplateApplication.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtProvider.java
  src/main/java/com/sparta/filmfly/global/config/WebConfig.java
  src/main/resources/application.yml
Labels: bug
