Repository film-fly/FilmFly, pull requests merged in 2024-08, with the labels that each got.

#260 영화 관리 기능
  build.gradle
  front/html/exam.html
  src/main/java/com/sparta/filmfly/domain/movie/controller/MovieController.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/ApiCreditsResponse.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/ApiCreditsResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/ApiGenresResponse.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/ApiMovieRequestDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/ApiMovieResponse.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/ApiMovieResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/CreditResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/GenresResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieDetailResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/PageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/SearchRequestDto.java
  src/main/java/com/sparta/filmfly/domain/movie/entity/Credit.java
  src/main/java/com/sparta/filmfly/domain/movie/entity/Genre.java
  src/main/java/com/sparta/filmfly/domain/movie/entity/LanguagesEnum.java
  src/main/java/com/sparta/filmfly/domain/movie/entity/Movie.java
  src/main/java/com/sparta/filmfly/domain/movie/entity/MovieCredit.java
  src/main/java/com/sparta/filmfly/domain/movie/entity/MovieSearchTypeEnum.java
  src/main/java/com/sparta/filmfly/domain/movie/entity/OriginLanguageEnum.java
  src/main/java/com/sparta/filmfly/domain/movie/entity/SortByEnum.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/CreditRepository.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/CreditRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/CreditRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/GenreRepository.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieCreditRepository.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepository.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/movie/service/MovieService.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/common/util/JsonFormatter.java
  src/main/java/com/sparta/filmfly/global/config/OkHttpClientConfig.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/filmfly/global/exception/custom/detail/ApiRequestFailedException.java
  src/test/http/movie/GenresAPI.http
  src/test/http/movie/HttpMovieApiTest.http
  src/test/http/movie/영화 단건 조회.http
  src/test/http/movie/인기 영화 조회.http
  src/test/http/test.http
  src/test/http/로그인 관리자 계정.http
Labels: enhancement

#271 댓글 dto 수정 및 api 일부 개선
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentUpdateResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/entity/Comment.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentQueryRepository.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#278 [BUGFIX] 찜하기 버그 수정
  src/main/java/com/sparta/filmfly/domain/favorite/controller/FavoriteController.java
  src/main/java/com/sparta/filmfly/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/sparta/filmfly/domain/favorite/service/FavoriteService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/test/http/favorite/CreateFavorite.http
Labels: bug

#279 [BUGFIX] 보관함 버그 수정
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/MovieCollectionRequestDto.java
  src/main/java/com/sparta/filmfly/domain/collection/entity/MovieCollection.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/CollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/MovieCollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
  src/test/http/collection/Collection.http
Labels: bug

#280 [REFACTOR] 찜하기 성공시 id값 반환
  src/main/java/com/sparta/filmfly/domain/favorite/controller/FavoriteController.java
  src/main/java/com/sparta/filmfly/domain/favorite/dto/FavoriteResponseDto.java
  src/main/java/com/sparta/filmfly/domain/favorite/service/FavoriteService.java
Labels: enhancement

#283 [REFACTOR] MovieController URL을 복수형으로 변경
  src/main/java/com/sparta/filmfly/domain/movie/controller/MovieController.java
  src/test/http/movie/영화 단건 조회.http
  src/test/http/movie/영화 조회.http
Labels: enhancement

#288 페이징 요청, 응답값 통일
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/movie/controller/MovieController.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/PageResponseDto.java
  src/test/http/HttpCommentRequest.http
  src/test/http/movie/영화 조회.http
Labels: enhancement

#290 Review 페이징 구현
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewCreateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewUpdateRequestDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewUpdateResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/entity/Review.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
  src/test/http/reaction/ReactionHttp.http
  src/test/http/review/ReviewHttp.http
Labels: enhancement

#292 영화 단건 조회 시 리뷰의 평균 평점 구현
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieDetailResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/service/MovieService.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryImpl.java
Labels: enhancement

#293 운영보드 구조 변경
  src/main/java/com/sparta/filmfly/domain/file/service/FileService.java
  src/main/java/com/sparta/filmfly/domain/file/util/FileUtils.java
  src/main/java/com/sparta/filmfly/domain/officeboard/controller/OfficeBoardController.java
  src/main/java/com/sparta/filmfly/domain/officeboard/dto/OfficeBoardPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/officeboard/dto/OfficeBoardRequestDto.java
  src/main/java/com/sparta/filmfly/domain/officeboard/dto/OfficeBoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/officeboard/dto/OfficeBoardUpdateResponseDto.java
  src/main/java/com/sparta/filmfly/domain/officeboard/entity/OfficeBoard.java
  src/main/java/com/sparta/filmfly/domain/officeboard/service/OfficeBoardService.java
  src/main/java/com/sparta/filmfly/global/common/S3Uploader.java
  src/main/java/com/sparta/filmfly/global/util/FileUtils.java
Labels: enhancement

#298 프론트 일부 연결
  front/css/style.css
  front/html/board-detail.html
  front/html/board.html
  front/html/create-board.html
  front/html/create-collection.html
  front/html/create-review.html
  front/html/exam.html
  front/html/index.html
  front/html/login.html
  front/html/movie-detail.html
  front/html/movie.html
  front/html/mypage-bad.html
  front/html/mypage-block.html
  front/html/mypage-board.html
  front/html/mypage-collection-detail.html
  front/html/mypage-collection.html
  front/html/mypage-comment.html
  front/html/mypage-coupon.html
  front/html/mypage-favorite-movie.html
  front/html/mypage-good.html
  front/html/mypage-review.html
  front/html/mypage-update-password.html
  front/html/mypage-update-profile.html
  front/html/mypage-update.html
  front/html/mypage.html
  front/html/review-detail.html
  front/html/review-recently.html
  front/html/signup.html
  front/js/apiModule.js
  front/js/jquery.twbsPagination.js
  src/main/java/com/sparta/filmfly/domain/movie/controller/MovieController.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryImpl.java
Labels: enhancement

#303 feat 배포 및 api 수정
  .github/workflows/deploy.yml
  docker/Dockerfile
  src/main/java/com/sparta/filmfly/domain/movie/controller/MovieController.java
  src/main/java/com/sparta/filmfly/domain/movie/service/MovieService.java
  src/main/resources/bootsecurity.p12
  src/test/http/movie/GenresAPI.http
Labels: enhancement

#304 배포 오류 수정
  .github/workflows/deploy.yml
Labels: bug

#307 302 feat 더미 데이터 생성
  src/main/java/com/sparta/filmfly/dummytest/DataLoader.java
  src/main/resources/dummy/boardData.sql
  src/main/resources/dummy/commentData.sql
  src/main/resources/dummy/movieData.sql
  src/main/resources/dummy/reactionData.sql
  src/main/resources/dummy/reviewData.sql
  src/main/resources/dummy/userData.sql
  src/test/java/com/sparta/filmfly/dummytest/RandomEntityUserAndBoardAndCommentTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomReactionGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomReviewGeneratorTest.java
Labels: enhancement

#310 bugfix deploy error
  .github/workflows/deploy.yml
  docker/Dockerfile
  src/main/java/com/sparta/filmfly/SpringInitTemplateApplication.java
  src/main/java/com/sparta/filmfly/domain/test/TestController.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/config/AppConfig.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/favicon.ico
Labels: enhancement

#312 발표 전 front 수정
  front/common/common-header.html
  front/html/board-detail.html
  front/html/board.html
  front/html/create-board.html
  front/html/create-review.html
  front/html/movie-detail.html
  front/html/movie.html
  front/html/review-detail.html
  front/js/apiModule.js
  front/js/reaction.js
  front/js/summernote.js
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/MovieCollectionRequestDto.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/filmfly/domain/favorite/dto/FavoriteResponseDto.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtProvider.java
  src/main/java/com/sparta/filmfly/global/config/WebConfig.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
  src/main/resources/static/front/html/create-board.html
  src/main/resources/static/front/js/summernote.js
  src/test/http/HttpBoardRequest.http
  src/test/http/board/보드.http
  src/test/http/comment/HttpCommentRequest.http
  src/test/http/reaction/ReactionHttp.http
  src/test/http/review/ReviewHttp.http
Labels: enhancement

#313 더미 데이터 생성
  src/main/java/com/sparta/filmfly/dummytest/DataLoader.java
  src/main/resources/dummy/blockData.sql
  src/main/resources/dummy/boardData.sql
  src/main/resources/dummy/collectionData.sql
  src/main/resources/dummy/commentData.sql
  src/main/resources/dummy/favoriteData.sql
  src/main/resources/dummy/reportData.sql
  src/main/resources/dummy/reviewData.sql
  src/test/java/com/sparta/filmfly/dummytest/RandomBlockGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomCollectionGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomEntityUserAndBoardAndCommentTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomFavoriteGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomReportGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomReviewGeneratorTest.java
Labels: enhancement

#316 유저의 리뷰 목록 조회 기능 추가
  src/main/java/com/sparta/filmfly/domain/file/service/FileService.java
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
Labels: enhancement

#318 유저의 게시글 댓글 리뷰 목록 조회
  front/html/mypage-board.html
  front/html/mypage-review.html
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/entity/Board.java
  src/main/java/com/sparta/filmfly/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentPageResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
  src/main/resources/application.yml
Labels: enhancement

#319 apiModule.js 수정
  .gitignore
  front/html/board-detail.html
  front/html/board.html
  front/html/create-board.html
  front/html/signup.html
  front/js/apiModule.js
  front/js/summernote.js
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/dto/UserNicknameCheckRequestDto.java
Labels: enhancement

#320 영화관련 더미데이터 추가
  src/main/java/com/sparta/filmfly/dummytest/DataLoader.java
  src/main/resources/dummy/blockData.sql
  src/main/resources/dummy/boardData.sql
  src/main/resources/dummy/collectionData.sql
  src/main/resources/dummy/commentData.sql
  src/main/resources/dummy/creditData.sql
  src/main/resources/dummy/favoriteData.sql
  src/main/resources/dummy/genre.sql
  src/main/resources/dummy/movieCredit.sql
  src/main/resources/dummy/movieData.sql
  src/main/resources/dummy/movieGenreIds.sql
  src/main/resources/dummy/reactionData.sql
  src/main/resources/dummy/reportData.sql
  src/main/resources/dummy/reviewData.sql
  src/main/resources/dummy/userData.sql
  src/test/java/com/sparta/filmfly/dummytest/RandomEntityUserAndBoardAndCommentTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomReactionGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomReviewGeneratorTest.java
Labels: enhancement

#321 .http파일 전체적으로 통일
  src/test/http/HttpExamRequest.http
  src/test/http/HttpLoginTokenTest.http
  src/test/http/HttpOfficeBoardRequest.http
  src/test/http/HttpPasswordModifyTest.http
  src/test/http/board/보드.http
  src/test/http/collection/Collection.http
  src/test/http/comment/HttpCommentRequest.http
  src/test/http/favorite/CreateFavorite.http
  src/test/http/movie/GenresAPI.http
  src/test/http/movie/HttpMovieApiTest.http
  src/test/http/movie/영화 조회.http
  src/test/http/movie/인기 영화 조회.http
  src/test/http/reaction/ReactionHttp.http
  src/test/http/review/ReviewHttp.http
  src/test/http/test.http
  src/test/http/user/admin 활성화.http
  src/test/http/user/suspendUserTest.http
  src/test/http/user/탈퇴계정 활성화 test.http
  src/test/http/로그인 관리자 계정.http
  src/test/http/어드민 로그인.http
Labels: enhancement

#325 305 bugfix deploy error
  .github/workflows/deploy.yml
  .github/workflows/s3uploatd.yml
  front/html/signup.html
  src/main/java/com/sparta/filmfly/domain/movie/dto/ApiMovieRequestDto.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieCreditRepository.java
  src/main/java/com/sparta/filmfly/domain/movie/service/MovieService.java
  src/main/java/com/sparta/filmfly/domain/test/TestController.java
  src/main/java/com/sparta/filmfly/dummytest/DataLoader.java
  src/main/resources/bootsecurity.p12
  src/main/resources/static/favicon.ico
  src/test/http/movie/HttpMovieApiTest.http
Labels: bug, enhancement

#327 크롤링 업데이트
  src/main/java/com/sparta/filmfly/domain/movie/controller/MovieController.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/ApiDiscoverMovieRequestDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/ApiSearchMovieRequestDto.java
  src/main/java/com/sparta/filmfly/domain/movie/service/MovieService.java
  src/test/http/movie/HttpMovieApiTest.http
Labels: bug

#330 프론트 연결 (유저의 리뷰, 보드, 댓글 목록 조회)
  front/html/mypage-board.html
  front/html/mypage-comment.html
  front/html/mypage-review.html
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/entity/Comment.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
Labels: enhancement

#332 영화 검색 옵션 적용 완료
  front/html/movie.html
  src/main/java/com/sparta/filmfly/domain/movie/controller/MovieController.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieReactionsResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieSearchCond.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/movie/service/MovieService.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/GoodMovieResponseDto.java
  src/main/java/com/sparta/filmfly/global/common/response/PageResponseDto.java
Labels: enhancement

#333 프론트 연결 (유저의 찜 목록)
  front/html/mypage-favorite-movie.html
  front/html/mypage-review.html
  src/main/java/com/sparta/filmfly/domain/favorite/controller/FavoriteController.java
  src/main/java/com/sparta/filmfly/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/sparta/filmfly/domain/favorite/service/FavoriteService.java
Labels: enhancement

#336 사용자가 좋아요, 싫어요를 누른 목록 조회
  front/html/mypage-bad.html
  front/html/mypage-good.html
  front/html/review-detail.html
  front/js/apiModule.js
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieSimpleResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepository.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/reaction/controller/BadController.java
  src/main/java/com/sparta/filmfly/domain/reaction/controller/GoodController.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/GoodRequestDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/ReactionBoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/ReactionCommentResponseDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/ReactionMovieResponseDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/ReactionReviewResponseDto.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/BadRepository.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/BadRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/BadRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/GoodRepository.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/GoodRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/GoodRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/BadService.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/GoodService.java
  src/main/java/com/sparta/filmfly/domain/reaction/service/ReactionService.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/test/http/reaction/ReactionHttp.http
  src/test/http/reaction/리액션조회.http
Labels: enhancement

#337 index 페이지 제작 및 관련 API 수정
  front/html/index.html
  front/js/apiModule.js
  src/main/java/com/sparta/filmfly/domain/movie/controller/MovieController.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/ApiSearchMovieRequestDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/GenresResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/service/MovieService.java
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/test/http/movie/HttpMovieApiTest.http
Labels: enhancement

#340 335 feat 마이페이지 front
  front/html/mypage.html
  src/main/java/com/sparta/filmfly/domain/coupon/scheduler/CouponScheduler.java
  src/main/java/com/sparta/filmfly/domain/user/controller/UserController.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
Labels: enhancement

#343 보관함 프론트 연결
  front/html/create-collection.html
  front/html/mypage-board.html
  front/html/mypage-collection-detail.html
  front/html/mypage-collection.html
  front/html/mypage-comment.html
  front/html/mypage-favorite-movie.html
  front/html/mypage-review.html
  front/js/apiModule.js
  front/js/mypageCommon.js
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/CollectionWithUserResponseDto.java
  src/main/java/com/sparta/filmfly/domain/collection/entity/Collection.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/CollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/MovieCollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
Labels: enhancement

#347 Security Filter 수정
  front/html/index.html
  front/html/movie-detail.html
  front/html/movie.html
  front/html/mypage-bad.html
  front/html/mypage-collection-detail.html
  front/html/mypage-favorite-movie.html
  front/html/mypage-good.html
  front/html/review-detail.html
  front/js/apiModule.js
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/movie/controller/MovieController.java
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/user/service/KakaoService.java
  src/main/java/com/sparta/filmfly/global/auth/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/filmfly/global/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/filmfly/global/auth/JwtProvider.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
Labels: enhancement

#351 front 영화 보관함 기능 연결
  front/html/create-collection.html
  front/html/movie-detail.html
  front/html/mypage-review.html
  front/js/reaction.js
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/CollectionStatusResponseDto.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
Labels: enhancement

#353 feat front s3 deploy
  .github/workflows/DeployFront.yml
  .github/workflows/DeployServer.yml
  .github/workflows/s3uploatd.yml
Labels: deploy

#354 front mypage 상세 디자인
  front/css/style.css
  front/html/adminpage-coupon-management.html
  front/html/board-detail.html
  front/html/movie-detail.html
  front/html/mypage-board.html
  front/html/mypage-collection-detail.html
  front/html/mypage-collection.html
  front/html/mypage-comment.html
  front/html/mypage-favorite-movie.html
  front/html/mypage-review.html
  front/js/summernote.js
Labels: enhancement

#349 유저 프로필 비밀번호 변경 프론트 구현
  front/common/common-header.html
  front/html/login.html
  front/html/mypage-update-password.html
  front/html/mypage-update-profile.html
  front/html/mypage-update.html
  front/html/mypage.html
  front/html/signup.html
  front/js/apiModule.js
  front/js/common.js
Labels: enhancement

#356 좋아요, 싫어요, 찜하기 프론트 백 연결
  front/html/board-detail.html
  front/html/movie-detail.html
  front/js/apiModule.js
  front/js/reaction.js
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardReactionResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
  src/main/java/com/sparta/filmfly/domain/movie/controller/MovieController.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/CreditSimpleResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieCreditResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieDetailSimpleResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieReactionCheckResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/dto/MovieSimpleResponseDto.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepository.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/movie/service/MovieService.java
  src/main/java/com/sparta/filmfly/domain/reaction/controller/GoodController.java
  src/main/java/com/sparta/filmfly/domain/reaction/dto/ReactionCheckResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewReactionCheckResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
  src/main/java/com/sparta/filmfly/global/common/response/ResponseCodeEnum.java
Labels: enhancement

#357 335 feat 마이페이지 front
  front/html/mypage-block.html
  front/html/mypage.html
  front/js/apiModule.js
Labels: enhancement

#361 feat-데이터-크롤링-batch-파일-생성
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/sparta/filmfly/SpringInitTemplateApplication.java
  src/main/java/com/sparta/filmfly/domain/movie/service/MovieService.java
  src/main/java/com/sparta/filmfly/global/common/batch/JobCompletionListener.java
  src/main/java/com/sparta/filmfly/global/common/batch/MovieCrawlingScheduler.java
  src/main/java/com/sparta/filmfly/global/common/batch/MovieCrawlingTasklet.java
  src/main/java/com/sparta/filmfly/global/common/batch/MovieSearchTasklet.java
  src/main/java/com/sparta/filmfly/global/config/BatchConfig.java
  src/main/resources/application.yml
Labels: enhancement

#363 DB softDelete to hardDelete
  src/main/java/com/sparta/filmfly/domain/block/repository/BlockRepository.java
  src/main/java/com/sparta/filmfly/domain/board/repository/BoardRepository.java
  src/main/java/com/sparta/filmfly/domain/collection/repository/CollectionRepository.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/filmfly/domain/coupon/repository/CouponRepository.java
  src/main/java/com/sparta/filmfly/domain/officeboard/repository/OfficeBoardRepository.java
  src/main/java/com/sparta/filmfly/domain/report/repository/ReportRepository.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/filmfly/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/common/batch/crawling/MovieCrawlingScheduler.java
  src/main/java/com/sparta/filmfly/global/common/batch/crawling/MovieCrawlingTasklet.java
  src/main/java/com/sparta/filmfly/global/common/batch/crawling/MovieSearchTasklet.java
  src/main/java/com/sparta/filmfly/global/common/batch/hardDelete/HardDeleteScheduler.java
  src/main/java/com/sparta/filmfly/global/common/batch/hardDelete/HardDeleteTasklet.java
  src/main/java/com/sparta/filmfly/global/common/batch/hardDelete/SoftDeletableRepository.java
  src/main/java/com/sparta/filmfly/global/config/BatchConfig.java
  src/main/java/com/sparta/filmfly/global/config/BatchJobConfig.java
  src/main/java/com/sparta/filmfly/global/config/SchedulerConfig.java
Labels: enhancement

#366 [BUGFIX] 영화 등급 검색옵션 or로 변경
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepositoryImpl.java
Labels: bug

#367 수정, 삭제버튼 비활성화
  front/html/board-detail.html
  front/html/create-review.html
  front/html/movie-detail.html
  front/html/mypage-board.html
  front/html/mypage-collection-detail.html
  front/html/mypage-review.html
  front/html/mypage.html
  front/html/review-detail.html
  src/main/java/com/sparta/filmfly/domain/board/controller/BoardController.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardPageDto.java
  src/main/java/com/sparta/filmfly/domain/board/dto/BoardReactionResponseDto.java
  src/main/java/com/sparta/filmfly/domain/board/service/BoardService.java
  src/main/java/com/sparta/filmfly/domain/collection/controller/CollectionController.java
  src/main/java/com/sparta/filmfly/domain/collection/dto/CollectionWithUserResponseDto.java
  src/main/java/com/sparta/filmfly/domain/collection/service/CollectionService.java
  src/main/java/com/sparta/filmfly/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/comment/service/CommentService.java
  src/main/java/com/sparta/filmfly/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewReactionCheckResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/dto/ReviewUserResponseDto.java
  src/main/java/com/sparta/filmfly/domain/review/service/ReviewService.java
  src/main/java/com/sparta/filmfly/domain/user/entity/User.java
  src/main/java/com/sparta/filmfly/domain/user/service/UserService.java
  src/main/java/com/sparta/filmfly/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/sparta/filmfly/global/common/response/PageResponseDto.java
Labels: enhancement

#370 프론트 css
  front/css/style.css
  front/html/board-detail.html
  front/html/board.html
  front/html/create-board.html
  front/html/create-collection.html
  front/html/create-review.html
  front/html/index.html
  front/html/login.html
  front/html/movie-detail.html
  front/html/movie.html
  front/html/mypage-bad.html
  front/html/mypage-block.html
  front/html/mypage-board.html
  front/html/mypage-collection-detail.html
  front/html/mypage-collection.html
  front/html/mypage-comment.html
  front/html/mypage-coupon.html
  front/html/mypage-favorite-movie.html
  front/html/mypage-good.html
  front/html/mypage-review.html
  front/html/mypage-update-password.html
  front/html/mypage-update-profile.html
  front/html/review-detail.html
  front/html/review.html
  front/html/signup.html
  front/images/background-login.png
  front/js/reaction.js
Labels: enhancement

#371 [FEAT] 더미 데이터 변경
  front/html/movie-detail.html
  src/main/resources/dummy/blockData.sql
  src/main/resources/dummy/collectionData.sql
  src/main/resources/dummy/commentData.sql
  src/main/resources/dummy/favoriteData.sql
  src/main/resources/dummy/reactionData.sql
  src/main/resources/dummy/reportData.sql
  src/main/resources/dummy/reviewData.sql
  src/test/java/com/sparta/filmfly/dummytest/RandomBlockGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomCollectionGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomEntityUserAndBoardAndCommentTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomFavoriteGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomReactionGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomReportGeneratorTest.java
  src/test/java/com/sparta/filmfly/dummytest/RandomReviewGeneratorTest.java
Labels: enhancement

#372 게시물의 좋아요, 싫어요 수 버그 수정
  src/main/java/com/sparta/filmfly/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryImpl.java
Labels: bug

#373 Security 에러메세지 제대로 뜨게 수정
  src/main/java/com/sparta/filmfly/global/auth/CustomExceptionHandlingFilter.java
  src/main/java/com/sparta/filmfly/global/config/WebSecurityConfig.java
Labels: enhancement

#374 댓글 CRUD 버그 수정
  front/html/board-detail.html
  front/html/movie-detail.html
  front/js/common.js
  src/main/java/com/sparta/filmfly/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryImpl.java
Labels: bug

#375 영화,리뷰 좋아요,싫어요 수 버그 수정
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/movie/repository/MovieRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryImpl.java
Labels: bug

#376 좋아요,싫어요 수 버그 수정
  front/html/mypage.html
  src/main/java/com/sparta/filmfly/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/review/repository/ReviewRepositoryImpl.java
Labels: bug

#378 apiModule.js 구조 살짝 변경
  front/js/apiModule.js
Labels: enhancement

#380 favicon 추가
  front/css/style.css
  front/html/movie-detail.html
  src/main/java/com/sparta/filmfly/domain/reaction/repository/BadRepositoryImpl.java
  src/main/java/com/sparta/filmfly/domain/reaction/repository/GoodRepositoryImpl.java
  src/main/resources/static/favicon.ico
Labels: enhancement
